import React from 'react'
import Head from 'next/head'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-pink-50'>
        <h2 className='text-green-500'>Testing Tailwind test</h2>
      </main>
    </>
  )
}
